# -*- coding: utf-8 -*-
"""olx_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rS91lOI2YP9OEUjLF-7h1w-zhSGrg38L
"""

# url ==> https://www.olx.com.eg/ajax/misc/contact/phone/bYhjS/
# https://www.olx.com.eg/ajax/misc/contact/phone/{id}  
# https://www.olx.com.eg/ad/town-house-corner-307-m2-for-sale-in-vilette-IDbYhjS.html

# libs
from bs4 import BeautifulSoup as sp
from requests import get
import lxml
import json
import csv
from time import sleep
from IPython.display import clear_output

def get_phone(refurl):
    id = refurl[refurl.index('ID'):].strip('ID').strip('.html')
    h = {
        'accept': '*/*',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.9',
        'referer':refurl ,
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'

        }
    
    url = f'https://www.olx.com.eg/ajax/misc/contact/phone/{id}'
    phone = get(url,headers=h).content
    try:
        phone = json.loads(phone)['value'].replace(' ','')
        return phone
    except:
        pass  

def get_info(url):
  headers= {
                
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.9',
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
        }
  r = get(url,headers=headers)
  soup = sp(r.content,'lxml')
  name = soup.find('p',class_='user-box__info__name').text
  name = '_'+name+'_'
  phone = get_phone(url)
  data = [name,phone]
  return data

categories = ['vehicles', 'properties', 'mobile-phones-tablets-accessories-numbers', 'electronics-home-appliances', 'home-furniture-decor', 'fashion-beauty', 'pets', 'kids-babies', 'books-sports-hobbies', 'jobs', 'business-industrial-agriculture', 'services'] 
def get_ads(category,pages_count):
    name = []
    ads_links = []
    for page in range(pages_count):
        refurl= f'https://www.olx.com.eg/{category}/?page={page+1}'
        if page==1:
          refurl= f'https://www.olx.com.eg/{category}/'

        ajx_url = 'https://www.olx.com.eg/ajax/search/list/'
        print(f'=========={page+1}==========')
        print(refurl)
        headers= {
                
                'accept': '*/*',
                'accept-encoding': 'gzip, deflate, br',
                'accept-language': 'en-US,en;q=0.9',
                'referer':refurl,
                'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36'
                }
        response = get(ajx_url,headers=headers)
        soup = sp(response.content,'lxml')
        ads = soup.find_all('div',class_='ads__item__info')
        for ad in ads:
            ads_links.append(ad.a['href'] )
           
    return ads_links
        

  


def main():

    phones =[]
    for category in range(len(categories)):
      print( f"{category+1}- {categories[category]}")
    print('or press c for custom link')
    chose = input('chose your category by number: ')
    if chose=='c':
      category = input('slug: ')
    else:  
      category = categories[int(chose)-1]
    pages_count = int(input('chose your page count: '))
    ads_links = get_ads(category,pages_count)

    for ad in ads_links :
        
      phone = get_phone(ad)
      sleep(.1)
      print(phone)
      if phone != None:
          print(phone)
          phones.append(phone)
    print('done') 

    # final_phones = list(dict.fromkeys(phones))
    # phones_f = open(f'/content/drive/MyDrive/olx_data/phones_{category}_{pages_count}.txt','w')

    csv_file = open(f'/content/drive/MyDrive/olx_data/phones_{category}_{pages_count}.csv','w')
    # writer = csv.writer(csv_file)
    # writer.writerow(["Name", "Phone"])
    set(phones)
    for p in phones:
      
      csv_file.write(p+'\n')
    csv_file.close()
main()

get_info('https://www.olx.com.eg/ad/-IDbZ2QZ.html')

"""**advanced**

---




"""

def main1(chose,pages_count):

    
    # for category in range(len(categories)):
    #   print( f"{category}- {categories[category]}")
    # print('or press c for custom link')
    # chose = input('chose your category by number: ')
    if chose=='c':
      category = input('link or slug: ')
    global category
    # else:  
    category = categories[int(chose)]
    # pages_count = int(input('chose your page count: '))
    ads_links = get_ads(category,pages_count)
    return ads_links

def main2():
  i = 0
  csv_file = open(f'/content/drive/MyDrive/olx_data/phones_{category}_{pages_count}.csv','w')
  writer = csv.writer(csv_file)
  for ad in ads_links :
    phones =[]      
    phone = get_phone(ad)
    # nmn
    if phone != None:
      i=i+1 
      clear_output()
      print(i)
      writer.writerows(phone)
      phones.append(phone)
  print('done') 

  # final_phones = list(dict.fromkeys(phones))
  # phones_f = open(f'/content/drive/MyDrive/olx_data/phones_{category}_{pages_count}.txt','w')

  csv_file = open(f'/content/drive/MyDrive/olx_data/phones_{category}_{pages_count}.csv','w')
  writer = csv.writer(csv_file)
  # writer.writerow(["Name", "Phone"])
  # for p in phones:
    
  writer.writerows(phones)
  csv_file.close()